### ISSUE TITLE
Create GetBookBuyLinks and GetEditionBuyLinks

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-books#3]
Currently, GetBuyLinks which we use for the buylinks view only prints the latest edition buylinks.

This means the module is not capable of buylinks for every editions of the books. 

We should:

Create a GetEditionBuyLinks which will take the edition as context and return the buy links data
Create a GetLatestBuyLinks which could optionally returns all the book buylinks, or just the latest edition.
Create a view to display all buylinks from multiple editions.

**Comment by budparr** [comment]
Typically we only want buy links for the most current edition and the ebook. Books are typically released with hardcover first, then some time later the paperback is released (except when the book is released in paperback only).

**Comment by regisphilibert** [comment]
Oh ok good to know.
